<?php
/**
 * M-Pesa Blocks Script Asset File
 *
 * Defines dependencies and version for the blocks script. The version tracks
 * the plugin version so browsers re-fetch the script after an update (this
 * file is hand-written, not generated by a build tool, so nothing else keeps
 * the version current).
 */

if (!defined('ABSPATH')) {
    exit;
}

return [
    'dependencies' => [
        'wc-blocks-registry',
        'wc-settings',
        'wp-element',
        'wp-html-entities',
        'wp-i18n',
    ],
    'version' => defined('MARUPURUPU_VERSION') ? MARUPURUPU_VERSION : '1.0.0',
];
